# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Projects\InvoiceExtractor\ui\ui_loggerconsole.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loggerConsole(object):
    def setupUi(self, loggerConsole):
        loggerConsole.setObjectName("loggerConsole")
        loggerConsole.resize(571, 234)
        self.verticalLayout = QtWidgets.QVBoxLayout(loggerConsole)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(loggerConsole)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 571, 234))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.plainTextEdit.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout_2.addWidget(self.plainTextEdit)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(loggerConsole)
        QtCore.QMetaObject.connectSlotsByName(loggerConsole)

    def retranslateUi(self, loggerConsole):
        _translate = QtCore.QCoreApplication.translate
        loggerConsole.setWindowTitle(_translate("loggerConsole", "Logger Console"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    loggerConsole = QtWidgets.QWidget()
    ui = Ui_loggerConsole()
    ui.setupUi(loggerConsole)
    loggerConsole.show()
    sys.exit(app.exec_())
